title: Wen Ziwen
description: My Personal Blog
author: Wen Ziwen
logo: /static/img/avatar.png
github: https://github.com/wziwen
about: Android Developer

baseurl: ""
url: ""

disqus_shortname: ""
google_analytics: ""

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
